spring:
  datasource:
    hikari:
      auto-commit: off
    driver-class-name: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/accounting_db}
    username: ${SPRING_DATASOURCE_USERNAME:username}
    password: ${SPRING_DATASOURCE_PASSWORD:password}
  jpa:
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        default_schema: socks_service
        ddl-auto: create-drop
  sql:
    init:
      mode: always
      schema-locations: classpath:db/schema.sql
      data-locations: classpath:db/data.sql